version: '3.1'

services:

  wp:
    container_name: ${PROJECT_NAME}_wp
    image: wordpress
    restart: unless-stopped
    ports:
      - ${PORT_WP}:80
    volumes:
      - wp_data:/var/www/html
      - ./${FOLDER_THEME}:/var/www/html/wp-content/themes/${FOLDER_THEME}
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads
    environment:
      WORDPRESS_DB_HOST: "${DB_HOST}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
    expose:
      - ${PORT_WP}

  db:
    container_name: ${PROJECT_NAME}_db
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - ${PORT_DB}:3306
    volumes:
      - db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    expose:
      - ${PORT_DB}
  pma:
    container_name: ${PROJECT_NAME}_pma
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${PORT_PMA}:80
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: db
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    links:
      - db
    expose:
      - ${PORT_PMA}

  permissions:
    container_name: ${PROJECT_NAME}_perm
    image: alpine:3.8
    depends_on:
      - wp
    restart: "no"
    networks:
      - default
    volumes:
      - wp_data:/var/www/html
    command: chown -Rf 33:33 /var/www/html/wp-content && chmod -R a=r,u+w,a+X /var/www/html/wp-content

volumes:
  wp_data:
  db_data:
