version: '3.1'

services:

  wp:
    container_name: ${PROJECT_NAME}_wp
    image: wordpress
    restart: unless-stopped
    ports:
      - ${PORT_WP}:80
    working_dir: /var/www/html
    volumes:
      - wp_data:/var/www/html
      - ./${FOLDER_THEME}:/var/www/html/wp-content/themes/${FOLDER_THEME}
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./startup.sh:/startup.sh
    entrypoint: /startup.sh
    environment:
      WORDPRESS_DB_HOST: "${DB_HOST}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
      VIRTUAL_HOST: wpbasetheme.com
      VIRTUAL_PORT: ${PORT_WP}
      LETSENCRYPT_HOST: wpbasetheme.com
      LETSENCRYPT_EMAIL: info@wpbasetheme.com
    expose:
      - ${PORT_WP}

  db:
    container_name: ${PROJECT_NAME}_db
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - ${PORT_DB}:3306
    volumes:
      - db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    expose:
      - ${PORT_DB}
  pma:
    container_name: ${PROJECT_NAME}_pma
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${PORT_PMA}:80
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: db
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    links:
      - db
    expose:
      - ${PORT_PMA}

volumes:
  wp_data:
  db_data:

networks:
  default:
    external:
      name: nginx-proxy
